module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "amber-100": "var(--amber-100)",
        "amber-200": "var(--amber-200)",
        "amber-400": "var(--amber-400)",
        "amber-50": "var(--amber-50)",
        "amber-500": "var(--amber-500)",
        "amber-600": "var(--amber-600)",
        "amber-700": "var(--amber-700)",
        "amber-800": "var(--amber-800)",
        "amber-900": "var(--amber-900)",
        black: "var(--black)",
        "blue-600": "var(--blue-600)",
        "blue-gray100": "var(--blue-gray100)",
        "blue-gray200": "var(--blue-gray200)",
        "blue-gray400": "var(--blue-gray400)",
        "blue-gray600": "var(--blue-gray600)",
        "blue-gray700": "var(--blue-gray700)",
        "blue-gray900": "var(--blue-gray900)",
        "blue-light700": "var(--blue-light700)",
        "cool-gray200": "var(--cool-gray200)",
        defaultalert: "var(--defaultalert)",
        defaultwhite: "var(--defaultwhite)",
        "fuchsia-700": "var(--fuchsia-700)",
        "green-100": "var(--green-100)",
        "green-500": "var(--green-500)",
        "green-700": "var(--green-700)",
        "green-800": "var(--green-800)",
        "indigo-600": "var(--indigo-600)",
        "lime-200": "var(--lime-200)",
        "lime-400": "var(--lime-400)",
        "overlaydark-75": "var(--overlaydark-75)",
        "pink-700": "var(--pink-700)",
        "purple-100": "var(--purple-100)",
        "purple-400": "var(--purple-400)",
        "purple-800": "var(--purple-800)",
        "red-100": "var(--red-100)",
        "red-400": "var(--red-400)",
        "red-800": "var(--red-800)",
        "rose-600": "var(--rose-600)",
        "violet-300": "var(--violet-300)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-l": "var(--body-l-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-s": "var(--body-s-font-family)",
        "body-XL": "var(--body-XL-font-family)",
        "body-XS": "var(--body-XS-font-family)",
        "body-XXL": "var(--body-XXL-font-family)",
        "button-l": "var(--button-l-font-family)",
        "button-m": "var(--button-m-font-family)",
        "button-s": "var(--button-s-font-family)",
        "button-XL": "var(--button-XL-font-family)",
        "caption-m": "var(--caption-m-font-family)",
        "heading-1-l": "var(--heading-1-l-font-family)",
        "heading-1-m": "var(--heading-1-m-font-family)",
        "heading-2": "var(--heading-2-font-family)",
        "heading-3": "var(--heading-3-font-family)",
        "heading-4": "var(--heading-4-font-family)",
        "heading-5": "var(--heading-5-font-family)",
        "heading-6": "var(--heading-6-font-family)",
        "subtitle-m": "var(--subtitle-m-font-family)",
        "subtitle-XL": "var(--subtitle-XL-font-family)",
        sans: [
          "Montserrat",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "shadow-dark-l": "var(--shadow-dark-l)",
        "shadow-dark-m": "var(--shadow-dark-m)",
        "shadow-dark-s": "var(--shadow-dark-s)",
        "shadow-dark-XL": "var(--shadow-dark-XL)",
        "shadow-dark-XXL": "var(--shadow-dark-XXL)",
        "shadow-light-XXL": "var(--shadow-light-XXL)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { 
      center: true, 
      padding: "2rem", 
      screens: { 
        "2xl": "1400px",
        "3xl": "1600px",
        "4xl": "1920px"
      } 
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
      '4xl': '2560px',
    },
  },
  plugins: [],
  darkMode: ["class"],
};